CREATE TABLE CLINIC
(
	'NAME' VARCHAR(50) NOT NULL,
	'CITY' VARCHAR(50) NOT NULL,
	PRIMARY KEY('NAME','CITY')
);
CREATE TABLE DOCTOR
(
	'PHYS_SSN' INTEGER NOT NULL PRIMARY KEY,
	'SPECIALTY' VARCHAR(50),
	'NAME' VARCHAR(50) NOT NULL,
	'EXPERIENCE' VARCHAR(100),
	KEY 'CLINIC_ID' ('CLINIC_ID'),
	FOREIGN KEY ('CLINIC_ID') REFERENCES CLINIC ('')
);
CREATE TABLE PATIENT
(
	'PATIENTSSN' INTEGER NOT NULL PRIMARY KEY,
	'AGE' INTEGER NOT NULL,
	'NAME' VARCHAR NOT NULL,
	'ADDRESS' VARCHAR(100) NOT NULL,
	UNIQUE INDEX 'ADDRESS_UNIQUE' ('ADDRESS' ASC),

);
CREATE TABLE PRESCRIPTION
(
);
CREATE TABLE DRUG
(
);
CREATE TABLE PHARMACY
(
);
CREATE TABLE DRUGCOMPANY
(
);
CREATE TABLE INSTORE
(
);
CREATE TABLE ONLINE
(
);
CREATE TABLE PRESCRIBES
(
);
CREATE TABLE PRESCRIPTION_AND_DRUG
(
);
CREATE TABLE SELL
(
);
CREATE TABLE CONTRACT
(
);