CREATE TABLE R
(
	A INTEGER NOT NULL PRIMARY KEY,
	B INTEGER NOT NULL,
	C INTEGER NOT NULL
);
CREATE TABLE S
(
	D INTEGER NOT NULL,
	E INTEGER NOT NULL,
	F INTEGER NOT NULL REFERENCES R(A) ON DELETE CASCADE ON UPDATE SET NULL,
	PRIMARY KEY(D,E)
);
CREATE TABLE T
(
	G INTEGER NOT NULL PRIMARY KEY,
	H INTEGER NOT NULL,
	I INTEGER NOT NULL
);
CREATE TABLE Y
(
	M INTEGER NOT NULL REFERENCES S(D) ON DELETE CASCADE ON UPDATE SET NULL,
	N INTEGER NOT NULL REFERENCES S(E) ON DELETE CASCADE ON UPDATE SET NULL,
	O INTEGER NOT NULL REFERENCES T(G) ON DELETE CASCADE ON UPDATE SET NULL,
	P INTEGER NOT NULL,
	PRIMARY KEY(M,N,O)
);
CREATE TABLE Z
(
	J INTEGER NOT NULL REFERENCES R(A) ON DELETE CASCADE ON UPDATE SET NULL,
	K INTEGER NOT NULL REFERENCES T(G) ON DELETE CASCADE ON UPDATE SET NULL,
	L INTEGER NOT NULL,
	PRIMARY KEY(J,K)
);
