CREATE TABLE R
(
	A INTEGER NOT NULL PRIMARY KEY
	B INTEGER NOT NULL,
	C INTEGER NOT NULL
);
CREATE TABLE S
(
	D INTEGER NOT NULL,
	E INTEGER NOT NULL,
	F INTEGER NOT NULL REFERENCES R(A),
	PRIMARY KEY(D,E)
);
CREATE TABLE T
(
	G INTEGER NOT NULL PRIMARY KEY
	H INTEGER NOT NULL,
	I INTEGER NOT NULL
);
CREATE TABLE Y
(
	M INTEGER NOT NULL REFERENCES S(D),
	N INTEGER NOT NULL REFERENCES S(E),
	O INTEGER NOT NULL REFERENCES T(G),
	P INTEGER NOT NULL,
	PRIMARY KEY(M,N,O)
);
CREATE TABLE Z
(
	J INTEGER NOT NULL REFERENCES R(A),
	K INTEGER NOT NULL REFERENCES T(G),
	L INTEGER NOT NULL
	PRIMARY KEY(J,K)
);
