import pymysql
import simplejson as json
from parse import *

if __name__ == '__main__':
	file_contents = open('creds.json').read()
	file_contents = json.loads(file_contents)	

	connection = pymysql.connect(**file_contents)
	cursor = connection.cursor()

	print('SELECT COUNT(*) FROM Attributes')
	cursor.execute('SELECT COUNT(*) FROM Attributes')
	print(cursor.fetchall())
	print('SELECT COUNT(*) FROM Attributes_Int_Value')
	cursor.execute('SELECT COUNT(*) FROM Attributes_Int_Value')
	print(cursor.fetchall())
	print('SELECT COUNT(*) FROM Attributes_VarChar_Value')
	cursor.execute('SELECT COUNT(*) FROM Attributes_VarChar_Value')
	print(cursor.fetchall())
	print('SELECT COUNT(*) FROM Business')
	cursor.execute('SELECT COUNT(*) FROM Business')
	print(cursor.fetchall())
	print('SELECT COUNT(*) FROM Category')
	cursor.execute('SELECT COUNT(*) FROM Category')
	print(cursor.fetchall())
	print('SELECT COUNT(*) FROM CheckIn')
	cursor.execute('SELECT COUNT(*) FROM CheckIn')
	print(cursor.fetchall())
	print('SELECT COUNT(*) FROM Compliment')
	cursor.execute('SELECT COUNT(*) FROM Compliment')
	print(cursor.fetchall())
	print('SELECT COUNT(*) FROM Days_of_Week')
	cursor.execute('SELECT COUNT(*) FROM Days_of_Week')
	print(cursor.fetchall())
	print('SELECT COUNT(*) FROM Elite')
	cursor.execute('SELECT COUNT(*) FROM Elite')
	print(cursor.fetchall())
	print('SELECT COUNT(*) FROM Friendship')
	cursor.execute('SELECT COUNT(*) FROM Friendship')
	print(cursor.fetchall())
	print('SELECT COUNT(*) FROM Review')
	cursor.execute('SELECT COUNT(*) FROM Review')
	print(cursor.fetchall())
	print('SELECT COUNT(*) FROM User')
	cursor.execute('SELECT COUNT(*) FROM User')
	print(cursor.fetchall())
	print('SELECT COUNT(*) FROM child_attributes')
	cursor.execute('SELECT COUNT(*) FROM child_attributes')
	print(cursor.fetchall())

	connection.commit()
	cursor.close()
	connection.close()